### ISSUE TITLE
(ql:quickload "sdl2") hangs the REPL; cannot install

### ISSUE THREAD

**Issue by willosborne** [lispgames/cl-sdl2#110]
First encountered this issue with the sketch library (https://github.com/vydd/sketch), and again with cl-sdl2.
I'm running SBCL 1.4.7 on Ubuntu.
Running "(ql:quickload "sdl2")"  gives me the following:

* (ql:quickload "sdl2")           
To load "sdl2":
  Load 1 ASDF system:
    sdl2
; Loading "sdl2"
....

....and it hangs there. Nothing more happens - but I can Ctrl-C out of it. I've got libSDL2 and all dependencies installed via apt-get (pretty sure!), so that shouldn't be an issue.
This doesn't happen with all quicklisp packages - for example, cl-ppcre works just fine.

Does anyone have any idea what might be wrong - or how I could possibly debug this?

Here's the full dump with restarts:
`* (ql:quickload "sdl2")
To load "sdl2":
  Load 1 ASDF system:
    sdl2
; Loading "sdl2"
......^C
debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {10005585B3}>:
  Interactive interrupt at #x227B9659.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Return from SB-UNIX:SIGINT.
  1: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "sdl2" "autowrap">.
  2: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "sdl2" "autowrap">
                                     as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the
                                     configuration.
  7: [ABORT                        ] Give up on "sdl2"
  8:                                 Exit debugger, returning to top level.

(CL-PPCRE::CREATE-BMH-MATCHER #<unavailable argument> #<unavailable argument>)
0] 
`

**Comment by mfiano** [comment]
Did you try `(ql:quickload :sdl2 :verbose t)`?

**Comment by willosborne** [comment]
Sorry - tried it with verbose on and got this: 
* (ql:quickload :sdl2 :verbose t)
To load "sdl2":
  Load 1 ASDF system:
    sdl2
; Loading "sdl2"
WARNING: System definition file #P"/home/will/quicklisp/dists/quicklisp/software/cl-json-20141217-git/cl-json.asd" contains definition for system "cl-json.test". Please only define "cl-json" and secondary systems with a name starting with "cl-json/" (e.g. "cl-json/test") in that file.
WARNING: System definition file #P"/home/will/quicklisp/dists/quicklisp/software/trivial-garbage-20150113-git/trivial-garbage.asd" contains definition for system "trivial-garbage-tests". Please only define "trivial-garbage" and secondary systems with a name starting with "trivial-garbage/" (e.g. "trivial-garbage/test") in that file.
..STYLE-WARNING:
   Generic function CL-PPCRE::STR clobbers an earlier FTYPE proclamation
   (FUNCTION (T) (VALUES SIMPLE-STRING &REST T)) for the same name with
   (FUNCTION (T) *).
.WARNING: redefining DEFPACKAGE-PLUS-1::DEFPACKAGE+-DISPATCH in DEFGENERIC
.WARNING:
   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:LOAD-OP
   '("swank")) while visiting (ASDF/LISP-ACTION:LOAD-OP "sdl2" "optional-deps")
   - please use proper dependencies instead
.WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD

; compiling file "/home/will/quicklisp/dists/quicklisp/software/cl-sdl2-20180430-git/src/autowrap.lisp" (written 01 JUL 2018 09:16:46 PM):
; compiling (IN-PACKAGE :SDL2-FFI)
; compiling (AUTOWRAP:C-INCLUDE (QUOTE #) ...).

so does that mean it's hanging on the SDL 2 FFI part of the compile?

**Comment by mfiano** [comment]
It looks like you are using an older cl-sdl2. The version in Quicklisp is much too old for recent sdl2 versions, as Quicklisp hasn't been updated since April. Please try again with cl-sdl2 from git HEAD and post another log if it does not work.

**Comment by willosborne** [comment]
oh, my mistake! I'll install from Git and try again. Thanks very much!

**Comment by willosborne** [comment]
Okay, I cloned autowrap and cl-sdl2 as per the instructions in this repo's README and ran (ql:quickload "sdl2" :verbose t)
- exactly the same problem (stuck at compiling (AUTOWRAP:C-INCLUDE(QUOTE#) ...).

**Comment by willosborne** [comment]
Okay, it's magically fixed itself now! I left it hanging for about 10 minutes and it suddenly seemed to get unstuck and compiled it all! Thanks for your help - should I close this or is that delay still worth leaving up?

**Comment by mfiano** [comment]
Did you try clearing your FASL's?

**Comment by willosborne** [comment]
That might well have helped it, but the problem seemed to be very long compilation times more than anything else. Anyway, it's working now!
