### ISSUE TITLE
wrong version of sdl2?? Error: Incorrect keyword arguments in (:UNDERFLOW NIL :OVERFLOW NIL :INEXACT NIL :INVALID NIL :DIVIDE-BY-ZERO NIL :DENORMALIZED-OPERAND NIL) . 

### ISSUE THREAD

**Issue by ulrivo** [lispgames/cl-sdl2#119]
I installed cl-sdl2 on my Mac.

When I start clozure-cl (ccl64 1.11.6) and try to run the examples

   (ql:quickload :sdl2/examples)
   (sdl2-examples:basic-test)

the second command gives an error
.................................................................................................................................................
? (sdl2-examples:basic-test)
Using SDL Library Version: 2.0.8
Setting up window/gl.
> Error: Incorrect keyword arguments in (:UNDERFLOW NIL :OVERFLOW NIL :INEXACT NIL :INVALID NIL :DIVIDE-BY-ZERO NIL :DENORMALIZED-OPERAND NIL) .
> While executing: SET-FPU-MODE, in process Initial(0).

;;;
;;; #<PROCESS Initial(0) [Active] #x3020000BA84D> requires access to Shared Terminal Input
;;; Type (:y 0) to yield control to this thread.
;;;
.................................................................................................................................................

I found out that I installed SDL2 in the version 2.0.10 on my Mac (with brew), but not 2.0.8 as basic-test said.

The corresponding variable is

> sdl2-ffi:+sdl-patchlevel+
8

Regards,
Ulrich

**Comment by nsrahmad** [comment]
Hi, This bug had nothing to do with SDL version. This bug was in `float-features` library, which is already reported and fixed. See https://github.com/Shinmera/float-features/issues/6
