### ISSUE TITLE
with-rects and with-points are leaky

### ISSUE THREAD

**Issue by remexre** [lispgames/cl-sdl2#127]
they need an unwind-protect each to free the rect/point; this may apply to other structs as well.

**Comment by phoe** [comment]
A roughly created list of all `WITH-*` macros in the repository that might need to be checked:
```lisp
┌─[phoe][phoetower][±][master ✓][/tmp/cl-sdl2]
└─▪ git grep "defmacro with-"
src/events.lisp:(defmacro with-sdl-event ((event &optional (event-type :firstevent)) &body body)
src/events.lisp:(defmacro with-event-loop ((&key background (method :poll) (timeout nil) recursive)
src/rect.lisp:(defmacro with-points (bindings &body body)
src/rect.lisp:(defmacro with-rects (bindings &body body)
src/render.lisp:(defmacro with-renderer ((renderer-sym window &key index flags) &body body)
src/sdl2.lisp:(defmacro with-init ((&rest sdl-init-flags) &body body)
src/video.lisp:(defmacro with-window ((win
src/video.lisp:(defmacro with-everything ((&key window gl) &body body)
src/video.lisp:(defmacro with-gl-context ((gl-context-sym win) &body body)
```

**Comment by phoe** [comment]
This is related to https://github.com/lispgames/cl-sdl2/commit/329e0ccefff25e87985f188ee5dc88833a8da956 which removed finalizers from SDL objects - they seem to not be freed anywhere in the code now.

**Comment by izz-j** [comment]
Can confirm,  with-event-loop is very leaky. I haven't noticed any problem with any other macro. Inferior lisp returns seg faults until crash:

`Memory fault at (nil) (pc=0x7fabc6362a59, sp=0x7faba7aae680)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.`

**Comment by iamgreaser** [comment]
In `with-rects`, adding the `unwind-protect` / `free-rect` dance to `%with-rect` fixes the worst of the leaks.

`with-sdl-event` seems to be safe.

`with-points` and `let-rects` are both leaky at the moment.

**Comment by Halfwake** [comment]
Everything but  `with-rects`, `with-points`, and `with-event-loop` looks fine. `with-event-loop` may or may not be fine.
