### ISSUE TITLE
(sdl2-examples:basic-test) fails with "The alien function "SDL_Init" is undefined."

### ISSUE THREAD

**Issue by dakling** [lispgames/cl-sdl2#129]
When running `(sdl2-examples:basic-test)` after loading sdl2/examples, the error mentioned in the title appears. Under different circumstances, e.g. when trying to start cepl, a similar error claiming that `SDL_WasInit` is undefined.

I have ensured that sdl2 is installed, and I have also written a small C-file as a test, which, as far as I can tell, can call `SDL_WasInit` successfully. Any hints on how to debug this further?

I am running sdl2 (2.0.12-1) on Manjaro Linux (testing branch) with sbcl 2.0.3, if that matters.

**Comment by fitzsim** [comment]
This works for me on `SBCL 2.2.9.debian`.  Can you retry on the latest `Manjaro`?  Do remember if you had the SDL2 development headers package installed?  You will need that for `autowrap` to function.
