### ISSUE TITLE
Window never shows if launched from emacs

### ISSUE THREAD

**Issue by seoushi** [lispgames/cl-sdl2#130]
If I run the basic example via repl in emacs using sly I get no errors but the window never shows, I added some prints in the update loop and confirm that the update loop is running. This is on arch linux, gnome, doom emacs with sly, amd 3900x and radeon vii. The same code runs fine if I launch it though a terminal and not though emacs. This doesn't seem like a sly issue because if I run the code through eshell I have the same issue. Oddly enough on my laptop (lenovo T480) with intel graphics, arch linux and gnome it works just fine. I tried adding an extra (sdl2:show-window window) after init-with-window but that did not make a difference.

**Comment by mfiano** [comment]
Sorry but more information is needed. I cannot reproduce on Arch Linux, Doom Emacs, Sly, and a 3900x (though NVIDIA GTX 1080).

**Comment by seoushi** [comment]
My doom emacs was two months old and I hadn't done an doom upgrade/sync in a long time. Now my desktop works as expected. Tho my laptop was out of date by the same amount. I'm guessing there was just something configured badly on my desktop and the latest update fixed it. Thanks for looking.
