### ISSUE TITLE
Loading sdl2 on macOS Monterey fails: M1/arm64 not supported

### ISSUE THREAD

**Issue by dg1sbg** [lispgames/cl-sdl2#144]
(ql:quickload :sdl2)
To load "sdl2":
  Load 1 ASDF system:
    sdl2
; Loading "sdl2"
......

; file: /Users/goenninger/gbt Dropbox/gbt/00_prod/common-lisp/cl-sdl2/src/autowrap.lisp
; in: AUTOWRAP:C-INCLUDE '(SDL2 AUTOWRAP-SPEC "SDL2.h")
;     (AUTOWRAP:C-INCLUDE '(SDL2-FFI::SDL2 SDL2-FFI::AUTOWRAP-SPEC "SDL2.h")
;                         :ACCESSOR-PACKAGE :SDL2-FFI.ACCESSORS :FUNCTION-PACKAGE
;                         :SDL2-FFI.FUNCTIONS :SPEC-PATH
;                         '(SDL2-FFI::SDL2 SDL2-FFI::AUTOWRAP-SPEC)
;                         :EXCLUDE-SOURCES
;                         ("/usr/local/lib/clang/([^/]*)/include/(?!stddef.h)"
;                          "/usr/include/" "/usr/include/arm-linux-gnueabihf"
;                          "/usr/include/X11/")
;                         :INCLUDE-SOURCES
;                         ("stdint.h" "bits/types.h" "sys/types.h" "bits/stdint"
;                          "machine/_types.h" "SDL2")
;                         ...)
; --> PROGN EVAL-WHEN 
; ==>
;   (AUTOWRAP:DEFINE-WRAPPER SDL2-FFI::QADDR-T #<PACKAGE "SDL2-FFI">)
; 
; caught COMMON-LISP:ERROR:
;   (during macroexpansion of (AUTOWRAP:DEFINE-WRAPPER QADDR-T ...))
;   Undefined foreign type: QADDR-T

I had to tweak c2ffi to run on macOS Monterey under M1/arm64 but I still run into cl-autowrap issues. I also generated the SDL2.arm64 .... .spec file - so that's not the issue.

**Comment by ellisvelo** [comment]
Hello @dg1sbg ,

I hit the same error that you did. I made the following changes to get past the problem:  https://github.com/ellisvelo/cl-sdl2/blob/master/src/autowrap.lisp#L12-L26

The generated spec file worked for darwin/arm64, but I had to regenerate the spec for darwin/x86-64.

**Comment by justjoheinz** [comment]
@ellisvelo thanks for documenting the required changes regarding the files to include to overcome the qaddr_t issue. It works for me now as well, after some fiddling to get c2ffi installed. 

Hopefully someone will wrap this up now, as we have a working Apple M1 solution.

**Comment by fitzsim** [comment]
This should be fixed by #167.  Please reopen if it is not.
