### ISSUE TITLE
Window won't show up with the "Make sbcl + MacOS combo work" patch

### ISSUE THREAD

**Issue by VitoVan** [lispgames/cl-sdl2#146]
On macOS, with the latest source code, the basic-test window won't show up.

After revert this commit:

https://github.com/lispgames/cl-sdl2/commit/bd2c7fe5a6a36214441df9bc74742bb60a81a3d9

Everything goes well.

I'm not digging around this yet, just tried the reversion and it worked.

macOS: 10.15.7
SBCL: 2.1.9

**Comment by ellisvelo** [comment]
Hello @VitoVan ,

I ran into the same problem that you did. I've created https://github.com/lispgames/cl-sdl2/pull/148 which prevents the main thread from being interrupted and I can now run the example code.

**Comment by VitoVan** [comment]
> Hello @VitoVan ,
> 
> I ran into the same problem that you did. I've created #148 which prevents the main thread from being interrupted and I can now run the example code.

Thank you, may the peace be with you.

**Comment by ellisvelo** [comment]
You're welcome and may peace be with you too.

**Comment by mfiano** [comment]
Fixed
