### ISSUE TITLE
Will you make an SDL3 port?

### ISSUE THREAD

**Issue by Filipp-Druan** [lispgames/cl-sdl2#159]
Hello!
I found out today, what the third SDL library version has been released. Will you make an SDL3 port?
Thanks!

**Comment by anticrisis** [comment]
Just a note, as of today the current stable release of SDL is 2.28.4. I can't quite tell from https://libsdl.org/ if a stable SDL3 is imminent or a long-term goal.

**Comment by fitzsim** [comment]
I do not think anyone has plans to make `cl-sdl2` support `SDL3`.  I will close this for now.
