### ISSUE TITLE
Unable to see the window when running basic example from SLIME

### ISSUE THREAD

**Issue by sonelliot** [lispgames/cl-sdl2#23]
If I run `(sdl2-examples:basic-test)` from within SLIME then I don't see any window and the REPL hangs forever. Subsequently aborting the thread seems to leave it in a broken state and I need to kill SBCL and restart it from scratch. But if I run it from the command line using the SBCL executable then it works fine.

I am using SBCL 1.1.12 (x86) on Windows 8. Any help would be appreciated. I have been banging my head on this issue for a while and I really hope it isn't just something stupid I'm doing! :sob:

**Comment by resttime** [comment]
I surprisingly discovered the commonqt library shares the same issue and solution as well: https://github.com/commonqt/commonqt/issues/24

Perhaps there is an underlying issue with emacs or SLIME.
