### ISSUE TITLE
Loading Images / Converting Images

### ISSUE THREAD

**Issue by paines** [lispgames/cl-sdl2#35]
In order to load textures or something the SDL_LoadBMP + SDL_ConvertSurfaceFormat functions would be a great addition.

**Comment by rpav** [comment]
These should be trivial additions.  Note though if you're using GL (which is recommended, even for 2D), it's probably easier to use something like `cl-png` and load data into the texture directly rather than going through SDL2.

**Comment by paines** [comment]
Thank you for answering. I am aware of png-read and others, however I am not very successfull using them in combination with SDL2. I guess when I try to display something, then the data I read from the file is not in the same format as the display/renderer. That's why I am asking for a sdl load or convert function. maybe you can clear some things up. Thanks again!

**Comment by rpav** [comment]
I'm reopening this: I feel it's a legitimate request and if nothing else, some kind of example for image loading should be provided.  Adding the functions is also not problematic, I haven't swung back around to doing so (or, submit a PR of course!).

(Hey, you beat me to the punch as I was typing!)

**Comment by rpav** [comment]
Also, SDL_image 2.0 could probably be pulled in.

**Comment by rpav** [comment]
I added the above functions.  I haven't tested them, and I don't think it's a great solution for image loading; still need an example and, really, SDL_image.

**Comment by paines** [comment]
Thanks again for adding the 2 functions. I finally figured out how to use png-read with cl-sdl2/sdl2kit. 
```
(eval-when (:compile-toplevel :load-toplevel :execute)
  (asdf:load-system :png-read)
  (asdf:load-system :sdl2kit)
  (asdf:load-system :static-vectors))

(defparameter width 500)
(defparameter height 500)

(defstruct (image :conc-name) data width height depth pitch)

(defun load-png (path)
  (ignore-errors
    (let* ((png (png-read:read-png-file path))
           (data (png-read:image-data png))
	   (size (array-dimension data 2))
           (width (png-read:width png))
           (height (png-read:height png))
           (array (make-array (list height width) :element-type '(unsigned-byte 32))))
      (ecase (png-read:colour-type png)
        (:truecolor-alpha
         (dotimes (y height)
           (dotimes (x width)
             (setf (aref array y x) (logior (ash (aref data x y 0) 16)
                                            (ash (aref data x y 1) 8)
                                            (aref data x y 2)
                                            (ash (aref data x y 3) 24))))))
        (:truecolor
         (dotimes (y height)
           (dotimes (x width)
             (setf (aref array y x) (logior (ash (aref data x y 0) 16)
                                            (ash (aref data x y 1) 8)
                                            (aref data x y 2)
					    (ash #xFF 24)))))))
      (make-image :data array :width width :height height :depth size :pitch (* width size)))))

(defun render (renderer width height)
  (let* ((image (load-png "~/Dropbox/MarioSMBW.png")) ;from http://upload.wikimedia.org/wikipedia/en/9/99/MarioSMBW.png
	 (tex  (sdl2:create-texture renderer :argb8888 :streaming (width image) (height image)))
	 (pixels (static-vectors:make-static-vector (* (width image) (height image)) :element-type '(unsigned-byte 32) :initial-element 0))
	 (rect (sdl2:make-rect 0 0 (width image) (height image))))
	     

    (dotimes (y (height image))
      (dotimes (x (width image))
	(setf (aref pixels (+ (* y (width image)) x)) 
	      (aref (data image) y x))))
    (sdl2:update-texture tex (static-vectors:static-vector-pointer pixels) :width (pitch image))
    (sdl2:render-copy renderer tex :dest-rect rect) ;zoomed
    ;(sdl2:render-copy renderer tex)
    (sdl2:render-present renderer)
    (sdl2:destroy-texture tex)
    (static-vectors:free-static-vector pixels)))

(defun basic-test ()
  (sdl2:with-init (:everything)
    (multiple-value-bind (window renderer)
	(sdl2:create-window-and-renderer width height '(:shown))
      (sdl2:with-event-loop (:method :poll)
	(:keyup
	 (:keysym keysym)
	 (when (sdl2:scancode= (sdl2:scancode-value keysym) :scancode-escape)
	   (sdl2:push-event :quit)))
	
	(:idle
	 ()
	 (render renderer width height))       
	
	(:quit () t))
      (sdl2:destroy-renderer renderer)
      (sdl2:destroy-window window))))

(sdl2:make-this-thread-main (lambda () (basic-test)))
```
Maybe someone can test and confirm the loading of png. I have the feeling that something isn't quite right with the alpha channel.

**Comment by triggeredbiscuit** [comment]
I've been using sdl2 surface-width and surface-height to get the dimensions of the surface returned by sdl2-image:load-image. And i get invalid values. The reason i am doing this is because i need this data to make a gl texture

**Comment by rpav** [comment]
@triggeredbiscuit Unless this is directly related to the above, please file a separate issue with a more detailed example.

**Comment by triggeredbiscuit** [comment]
My fault I was accidently reading the sdl2:surface-height and surface-width concatenated.(face palm). These function return the valid dimensions for the surface returned by sdl2image
