### ISSUE TITLE
No output to *standard-output* showing from sdl2 thread from sdl2:with-init

### ISSUE THREAD

**Issue by MatthewRock** [lispgames/cl-sdl2#37]
Hey.

As I said in the topic, I can't output text to console when I'm in sdl2 thread. Take a look at the example:

``` lisp
(multiple-value-bind (major minor patch) (sdl2:version-wrapped)
       (format *standard-output* "Using SDL Library Version: ~D.~D.~D~%"
           major
           minor
           patch))
```

This correctly outputs version. However, if I run basic-test or this code:

``` lisp
(sdl2:with-init (:everything)
       (multiple-value-bind (major minor patch) (sdl2:version-wrapped)
         (format *standard-output* "Using SDL Library Version: ~D.~D.~D~%"
             major
             minor
             patch)
         (print "Hello, world!")
         (print "dada")))
```

Nothing is showing at all. I found a way to display to console, with this hack-thing:

``` lisp
(sdl2:make-this-thread-main (lambda ()
                       (sdl2:with-init (:everything)
                         (multiple-value-bind (major minor patch) (sdl2:version-wrapped)
                             (format *standard-output* "Using SDL Library Version: ~D.~D.~D~%"
                               major
                               minor
                               patch)))))
```

Then it prints output correctly. It's unsure for me why it is so, but that's not feature, I believe.

**Comment by rpav** [comment]
Yeah, this is a side effect of sdl2 stuff running in its own thread; your output will be showing up on your terminal (if you connect e.g. via slime) or your `*inferior-lisp*`, if you're having slime start your lisp.

This really should be fixed, I just haven't gotten around to it quite yet.

**Comment by TatriX** [comment]
Could you please mention this fact in the ```README```? I mean the fact that output will be in the ```*inferior-lisp*``` buffer not the ```*slime-repl*```.

**Comment by mfiano** [comment]
Closing as this is a dated issue and is expected behavior for SDL2 running in a separate thread.
