### ISSUE TITLE
Missing OS UI & no events - sbcl & osx again :)

### ISSUE THREAD

**Issue by cbaggers** [lispgames/cl-sdl2#42]
Hi folks, I pulled the latest and got the (basic-example) working on osx with sbcl so great work!

The rendering is definitely working as I can set the color of the triangle to `(sin *loop*)` and `incf` `*loop*` and the colors change smoothly. However I get no events and (Im guessing this is related) no system ui.

By system ui I mean minimize/close buttons etc. 
I tested `(make-instance 'simple-window) in sdlkit as well and got the same result. Not sure what to check next. Any ideas?

**Comment by cbaggers** [comment]
![noevents](https://cloud.githubusercontent.com/assets/1579326/7980662/8e18931c-0aa9-11e5-9daf-a78b0e83cc4b.png)

**Comment by cbaggers** [comment]
Also tried `(sdl2:make-this-thread-main (lambda () (sdl2-examples:basic-test)))` without joy

**Comment by rpav** [comment]
Cool!  Did you try `make-this-thread-main` from the *initial* SBCL thread created on the terminal or from slime...?  I could swear the former worked last I tried.  But beyond that I'd have to screw around with it since I'm not sure.

**Comment by cbaggers** [comment]
I did it from slime.

**Comment by cbaggers** [comment]
YES it works ok so for those needing to replicate I ran this in the terminal

    Baggers$ sbcl

    * (ql:quickload :swank)       
    * (swank:create-server)
    * (ql:quickload :sdl2kit-examples)
    * (sdl2:make-this-thread-main (lambda () (kit.sdl2:start)))

And then connected with slime-connect. And ran the following in the repl

    * (in-package :kit.sdl2.test)
    * (make-instance 'simple-window)

**Comment by cbaggers** [comment]
Thanks so much dude, cant wait to get playing with this tonight
