### ISSUE TITLE
Installation instructions won't work for CLISP

### ISSUE THREAD

**Issue by tjohnman** [lispgames/cl-sdl2#44]
Following the installation instructions in the README will end up in this:

``` lisp
[2]> (asdf:load-system :sdl2-examples)
;; Compiling file /home/*****/quicklisp/local-projects/cl-sdl2/examples/basic.lisp ...
*** - LOAD: A file with name SDL2 does not exist
The following restarts are available:
RETRY          :R1      Retry compiling #<CL-SOURCE-FILE "sdl2-examples" "basic">.
ACCEPT         :R2      Continue, treating compiling #<CL-SOURCE-FILE "sdl2-examples" "basic"> as having been successful.
ABORT          :R3      Abort main loop
```

**Comment by rpav** [comment]
Hmm, this appears to be CLISP, which is known to have issues.  Unfortunately I've had issues building a CLISP with all the necessary features to support this so testing has been limited.

With CCL and SBCL, I can't reproduce this, though.

**Comment by tjohnman** [comment]
SBCL works. Thanks for the heads up.

**Comment by ryukinix** [comment]
CLISP really don't works with that, same issue here. CLISP are outdated.

**Comment by mfiano** [comment]
This won't be fixed, as CLISP is both unmaintained and does not have the performance required for most uses of SDL2 applications.

**Comment by lstyrtmrnbd** [comment]
I wish this was mentioned somewhere up-front
