### ISSUE TITLE
Strange mouse issue on OSX

### ISSUE THREAD

**Issue by mfiano** [lispgames/cl-sdl2#47]
I'm not sure if this is a bug or not, but I received an issue reported in my project: axionix/tradewarz#1

The issue is when clicking, the cursor jumps to center, and also is not hidden.

I believe this is due to sdl2:set-relative-mouse-mode, but I cannot reproduce on Linux. On Linux, the cursor doesn't jump around, and relative mode hides the cursor anyway.

Can you possibly shed some light on this to understand what is happening differently on OSX/Linux? I do not have access to OSX to attempt fixing this.

**Comment by rpav** [comment]
This sounds like an SDL2 bug, and I see a few vague reports on similar but no real resolution.  Are you on the latest SDL2?  It might have been fixed at some point, but I'm not sure.

**Comment by mfiano** [comment]
Closing this as it cannot be reproduced.
