### ISSUE TITLE
DIVISION-BY-ZERO Signalled by (sdl2:with-init (:everything) ...)

### ISSUE THREAD

**Issue by rcaustin** [lispgames/cl-sdl2#68]
I keep running into an arithmetic error DIVISION-BY-ZERO signalled every time I try to run one of the examples, and when evaluating individual pieces, I found that sdl2:with-init seemed to be causing it, though I'm not sure why.

I'm running this on Arch using SBCL, and I tried downloading the packages multiple times through quicklisp just in case something went wrong.

I've tried searching elsewhere, but I can't seem to find anyone else who has mentioned this issue, so I'm thinking I've goofed something up along the way.  Any info or guidance you could provide would be greatly appreciated.

Please let me know if there's any more information I can provide that would help!

I'm using sdl2 2.0.4-2, sbcl 1.3.1-1, and the version of cl-sdl2 presently found on quicklisp (cl-sdl2-20160318-git).

**Comment by rpav** [comment]
I've just reintroduced `without-fp-traps`.  Can you test with this and see if it solves your issue?  (This isn't something you need to modify your code for; it's a purely internal change.)

**Comment by rcaustin** [comment]
Hey, that cleared it right up!  Thanks for the quick response!

**Comment by rpav** [comment]
Great. :)
