### ISSUE TITLE
README.md file example incorrect on windows|ccl system

### ISSUE THREAD

**Issue by rpherman** [lispgames/cl-sdl2#69]

**Comment by rpherman** [comment]
I had to change the following in the README.md file to get it working on my CCL install on Windows 64 (the '/' to '-' as follows):

```
(asdf:load-system :sdl2/examples)
(sdl2-examples:basic-test)
```

to this:

```
(asdf:load-system :sdl2-examples)
(sdl2-examples:basic-test)
```

**Comment by rpav** [comment]
Argh, thought I updated that.

**Comment by rpav** [comment]
Wait, you must have an old version.  Did you get this from Quicklisp, and have you updated your QL dist recently?

**Comment by rpherman** [comment]
I am reading the README.md from your site now.

**Comment by rpav** [comment]
But where did you get the *code*... the current README is actually correct for the current code.

**Comment by rpherman** [comment]
From QL dist, but I just installed QL. Am I missing something about updating it after a fresh install? Thanks.

**Comment by rpherman** [comment]
The code is correct; it is the example at the bottom of the README.md. If I type it in as currently written on github, it fails. When I change my CCL input to:

`(asdf:load-system :sdl2-examples)`

vs. what the README.md says:

`(asdf:load-system :sdl2/examples)`

It works.

**Comment by rpav** [comment]
This should be correct if you just updated QuickLisp.  However watch out if you have a previously-installed version of `cl-sdl2` somewhere that is overriding QL.  E.g.,

```lisp
(asdf:load-system :sdl2)
(asdf:system-definition-pathname :sdl2)
```

**Comment by rpav** [comment]
This just indicates you have an old version of cl-sdl2 somewhere.  There is no longer an `sdl2-examples.asd` in the dist, and if you look at [sdl2.asd](https://github.com/lispgames/cl-sdl2/blob/master/sdl2.asd#L57) you will see the current system name.

**Comment by rpherman** [comment]
The above returned:

"C:/Users/Robert/quicklisp/dists/quicklisp/software/cl-sdl2-20150709-git/sdl2.asd"

**Comment by rpav** [comment]
That is pretty ancient; try 

```lisp
(quicklisp:update-all-dists)`.

**Comment by rpherman** [comment]
On it right now. Thank you!

**Comment by rpherman** [comment]
Thanks! It worked. New at this: I imagine you close it, since I did the asking and you did the answering?

**Comment by rpav** [comment]
Doesn't matter, but sure. ;) Good luck with your project.
