### ISSUE TITLE
Unhandled exception 11 when doing sdl2:init on Wayland

### ISSUE THREAD

**Issue by rfolland** [lispgames/cl-sdl2#71]
I have a problem with cl-sdl2 running on Wayland/Weston. Often I get this error (this one from ccl):

Unhandled exception 11 at 0x7f6e19142cd3, context->regs at #x7f6e1a5de048
Exception occurred while executing foreign code
 at xkb_context_ref + 3
received signal 11; faulting address: (nil)
address not mapped to object
? for help
[5084] Clozure CL kernel debugger: 

sdl2:init sometimes succeeds, and then things work fine, but often (almost half the time I'd say) I get this fault. I need to call sdl2:init only when I do a modechange on a connected monitor, or at startup.

So, if I could restart instead of being stuck at the ccl kernel debugger it would be ok. But I have not found any way to proceed from the kernel debugger.

I tried sbcl, and it gives similar faults (SB-SYS:MEMORY-FAULT-ERROR).

When I run this under X11 on another machine (both are running Arch Linux) everything is fine. No problem there.

Some options I am thinking of:
1. Do some sanity checks before calling sdl2:init, so it succeds
2. Somehow recover from the kernel debugger, to try again until it succeeds (since it succeeds over half the time)
3. Make some kind of external watchdog, killing and starting the whole program when it hits the kernel debugger. I looked at the output of "ps", but could see not change in the state reported in Linux when my program is in the kernel debugger. Any way to find that out from an external program?

**Comment by rpav** [comment]
This seems like more of an SDL2 issue than cl-sdl2, especially if you're getting it in init.  

Possibly, Wayland may be pickier about which thread runs it, but I'm not familiar enough with it to know.  If (single-threaded) C programs run fine, but calling `(sdl2:init)` from emacs/slime/etc does not, this is probably the problem.

If demo C programs <i>also</i> segfault, there are bigger issues clearly.  I think "4. Solving the segfaulting issue" is probably the best solution. ;)

**Comment by rfolland** [comment]
Thanks, I started doing option 3 for the moment (need to get something working). My program runs a Hunchentoot server as well, so I just check that it responds. If not I wnat to kill the whole program and restart.
But I cannot seem to get the saved application (ccl:save-application) to stay running without calling (sleep n), Even after starting the Hunchentoot server and my SDL thread it exits. I also tried buildapp by Zach Beane, but I guess it is similar to using (ccl:save-application). In his examples he mentions having to use (sb-impl::toplevel-repl nil), maybe that is something I need for ccl?
I started a swank server as well, but my application justs exits. 
I realize this is no longer a cl-sdl2 question, but rather "How to keep an application running like a repl" . I would like to keep it running without disturbing the threads running, so I suspect a do-loop with sleep is not the best solution?

**Comment by rpav** [comment]
I'm not entirely sure what you're trying to do but this definitely doesn't seem cl-sdl2 related; perhaps pose your question to #lisp, or one of the various lisp forums.

If you are trying to dump an image of anything after SDL2 is initialized, this is highly likely to result in a crash when you restart, and is not supported (or necessary).

**Comment by rfolland** [comment]
Thanks, actually using a do loop seems to be good enough to keep the program running. 
I do not save the image after sdl2:init, only with a reference to a toplevel function which is run from the image.

There is one issue I see now though: I see a difference in a call to sdl2:push-user-event.
When starting my program from a normal ccl repl-session with swank, I connect with slime from a separate emacs session. Doing a (sdl2:push-user-event :my-event) from slime works ok and SDL responds to it.
But doing the exact same with my program running from a saved application is different. Everything starts up, but when I do a (sdl2:push-user-event :my-event) from the connected slime I get a type-error:
"The value #<A Dead Mac Pointer> is not of the expected type CCL:MACPTR"

I presume I somehow need to convert the type of the event signal to something acceptable to the foreign SDL? Strange that it somehow works when I connect to swank in a repl, but not when I connect to swank in the executable image.

So far I have only used the simplest user-event-types (not sending any strings or data), since I did not find any examples using push-user-event in the cl-sdl2 code.

**Comment by rfolland** [comment]
Hmm, the error message is:
`The value of #<A Dead Mac Pointer> is not of the expected type CCL:MACPTR`

**Comment by rfolland** [comment]
I did "number 4" from comment 2 above after all, which is of course the best way to handle it. The segfaulting happened with C as well. Found the problem with the help of guys in wayland bugzilla. A race condition in the initialization calls from sdl. I filed a bug with sdl now: https://bugzilla.libsdl.org/show_bug.cgi?id=3328.
