### ISSUE TITLE
SDL main thread and current package

### ISSUE THREAD

**Issue by mfiano** [lispgames/cl-sdl2#76]
I am wondering if the issues with threads/specials can be side-stepped for the case of IN-MAIN-THREAD, and if it is at all possible for it to manually control the value of _PACKAGE_. It would be really nice if:

``` lisp
(in-package :test-package)
(sdl2:in-main-thread () *package*)
```

could somehow return:

``` lisp
#<PACKAGE "TEST-PACKAGE">
```

instead of:

``` lisp
#<PACKAGE "COMMON-LISP-USER">
```

**Comment by rpav** [comment]
This is actually kinda easy .. just don't use a dynamic variable, or "reset it" on the other side:

```lisp
(in-package :test-package)

(let ((my-package *package*))
  (sdl2:in-main-thread ()
    (let ((*package* my-package))
      ..)))
```

**Comment by mfiano** [comment]
Closing this as it is not really an issue with cl-sdl2, and I forgot why I even required this :)
