### ISSUE TITLE
Texture-access Enum keys have the last letter of their names chopped off

### ISSUE THREAD

**Issue by PuercoPop** [lispgames/cl-sdl2#82]
```lisp
> (ql:quickload :sdl2)

> (slot-value (slot-value (autowrap::require-type 'sdl2-ffi:sdl-texture-access "map value ~S of enum ~S to value")
                        'autowrap::type)
            'autowrap::values)
; => ((:STATI . 0) (:STREAMIN . 1) (:TARGE . 2))
```

Note this doesn't appear to be the case with other users.

**Comment by mfiano** [comment]
Can you please specify your host and implementation/version?

**Comment by PuercoPop** [comment]
I'm using `SBCL, version 2a6ce7`, which is from Nov 9, between versions 1.3.11-12. I can reproduce in `CCL Version 1.12-dev-r16660  (LinuxX8664)` as well.

 Using `ubuntu 16.04`, `sdl2 version 2.0.4` (Version: 2.0.4+dfsg1-2ubuntu2)
 and `clang version 3.8.0-2ubuntu4`.

**Comment by mfiano** [comment]
Hmm, I cannot reproduce this issue on SBCL 1.3.11, SDL2 2.0.5, and Linux. We'll have to wait for oGMo to address this I think.

**Comment by PuercoPop** [comment]
The issue was I had an old-version of cl-autowrap hanging around in local-projects
