### ISSUE TITLE
SDL_SetSurfaceBlendMode is missing

### ISSUE THREAD

**Issue by syll-dev** [lispgames/cl-sdl2#90]
SDL_SetSurfaceBlendMode / set-surface-blend-mode seems missing in cl-sdl2.

sdl-set-surface-blend-node is defined (in sdl2-ffi.functions).

And +sdl-blendmode-add+ is present in sdl2-ffi but not exported by sdl2.

**Comment by mfiano** [comment]
This project is no longer actively maintained. If you can, and still need this, file a PR.

**Comment by mfiano** [comment]
I am closing this due to no response. If you feel like this should be addressed, please re-open and/or submit a PR.
