### ISSUE TITLE
get-renderer-output-size is commented in package.lisp

### ISSUE THREAD

**Issue by dxtr** [lispgames/cl-sdl2#94]
Why is that? Is it not working? Doesn't seem too complicated.

**Comment by rpav** [comment]
Not sure.. if you have a use for it—i.e. actual case verifying it works etc etc—uncomment, make sure it works, and PR!  `cl-sdl2` is kinda stone-soup that way. ;)

**Comment by dxtr** [comment]
I am actually using it in a project right now - will probably make a pull request soon!
